version: 2.1

jobs:
  prueba-uno :
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm build
      - run: chmod +x deploy.sh
      - run: ./deploy.sh

workflows:
  version: 2.1
  prueba:
    jobs:
      - prueba-uno